import type { Metadata } from "next"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"
import { AppClerkProvider } from "@/components/providers/app-clerk-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AppClerkProvider>
          {children}
          <Toaster />
        </AppClerkProvider>
      </body>
    </html>
  )
}
